version: '3.8'

services:
  app:
    build: .
    container_name: bingebox_omega
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ENABLE_CLUSTERING=true
    restart: unless-stopped
    healthcheck:
      test:["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
