[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
ENABLE_CLUSTERING = "true"
